CREATE TABLE Movies.MovieDirectors
(
   MovieID INT NOT NULL FOREIGN KEY
        REFERENCES Movies.Movie(MovieID),
   DirectorID INT NOT NULL FOREIGN KEY
        REFERENCES Movies.Directors(DirectorID),
   Salary FLOAT NOT NULL,
   IsRemoved INT NOT NULL DEFAULT(0),
   CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
   UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())

   PRIMARY KEY(MovieID, DirectorID)
);