CREATE TABLE Movies.Movie
(
   MovieID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
   MovieName NVARCHAR(64) NOT NULL UNIQUE,
   Genre1 NVARCHAR(64) NOT NULL,
   Genre2 NVARCHAR(64),
   Genre3 NVARCHAR(64),
   ReleaseDate DATETIME2(0) NOT NULL,
   CostOfProduction FLOAT NOT NULL,
   IsRemoved INT NOT NULL DEFAULT(0),
   CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
   UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);