CREATE TABLE Movies.Cinema
(
   CinemaID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
   [State] NVARCHAR(64) NOT NULL,
   City NVARCHAR(64) NOT NULL,
   [Address] NVARCHAR(64) NOT NULL UNIQUE,
   IsRemoved INT NOT NULL DEFAULT(0),
   CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
   UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);